DockerでPython環境を導入
au-niji/ip_rejector pull request #2
Opened 2020-10-09 15:56 UTC by au-niji

DockerでPython環境を導入しました。

# 起動方法
`$ docker-compose up -d`
`$ docker-compose exec app bash`

2020-10-10 10:19 UTC, cacapon requested changes
構成自体は問題なさそうですが、折角pytestまで入れているので
実際にこのコンテナ環境でpytestまで実行できるか確認してもらってもよろしいでしょうか？

後で、この構成だと確認できなかった！ってなるよりかは、
このタイミングで分かった方がいいと思うので。

2020-10-10 10:25 UTC, Amazingengine-yoshitaka commented on docker-compose.yml
> +        image: ip_rejector_app:${application_tag}
@cacapon bamboo_app にしておいたら。

2020-10-10 10:46 UTC, cacapon commented on docker-compose.yml
> +        image: ip_rejector_app:${application_tag}
@Amazingengine-yoshitaka コンテナ一つだけだったら、これが一意になるのでappでいいと思います。
複数増やすの前提なら変えるべきでしょう。

長いとコンテナ起動時に文字入力面倒ですし。(Dockerのコンテナ名はタブ候補で出ない)

2020-10-10 12:47 UTC, au-niji commented on docker-compose.yml
> +        image: ip_rejector_app:${application_tag}
@cacapon cc @Amazingengine-yoshitaka
僕自身原理はわかっていませんが、起動などは「app」だけでできます。
ただ、コンテナ数もこれ以上増えないので「app」でも問題ないようにも感じますね・・・。

2020-10-10 12:49 UTC, au-niji commented
@cacapon 
pytestの実行の確認は、dockerコンテナ内でimportできるのかの確認だけで大丈夫でしょうか。
それとも、testフォルダ内にファイルを作り、テストが通るかやったほうがいいですか？

2020-10-10 15:19 UTC, cacapon commented
@au-niji 返答が遅くなりました。
testフォルダ作成してテスト通るかまで確認したほうがよろしいかと。

ダミーでもなんでもいいので、pytestで確認できるってなったらunittestの環境としてはオッケーかなと
私は思います。

2020-10-11 15:30 UTC, au-niji commented
@au-niji 
返信ありがとうございます。
pytestで確認できるようにしてから再度コミットします。

2020-10-11 16:01 UTC, au-niji commented
@cacapon 
Docker環境でpytestが通るように修正しました。
こちらのサイトのコードを利用してダミーファイル(app.py)に書いています。
https://rinatz.github.io/python-book/ch08-02-pytest/

また、pytestは以前のバージョンだと追加でライブラリを導入しなければならなかったので、バージョンを新しいものに変更しました。

# テスト起動方法
>>
$ docker-compose up -d
$ docker-compose exec app pytest ../test/module_test/test_app.py
<<

2020-10-12 08:20 UTC, Amazingengine-yoshitaka approved these changes
@au-niji pytest の箇所に関しては LGTM

2020-10-13 02:22 UTC, Amazingengine-yoshitaka commented on docker-compose.yml
> +        container_name: bamboo_app
@au-niji この項目を追加した意味は有りますか。

2020-10-14 08:30 UTC, Amazingengine-yoshitaka commented
@au-niji LGTM

2020-10-14 08:46 UTC, merged