コマンドを書き込む機能を実装
au-niji/ip_rejector pull request #5
Opened 2020-10-16 10:09 UTC by au-niji

# 概要
`application/reject/`の`reject_by_country.gcsh_`に、規定のコマンドに国名・連番・最大250個に分割したIP addressを付与したコマンドを書き込むようにしました。
ファイルがなければ作られるようになっています。(テスト済み)

# 確認方法
.envファイル内のexecution_env=PRODに設定
`$ docker-compose up -d`
`$ docker-compose exec app bash`
`$ python module/write_reject_command.py`
テストの場合は`execution_env=test`に設定
`pytest ../test/module_test/test_write_reject_command.py`

# 懸念点
次に、app.pyで全ての機能が連携したものを一度の実行できるようにしたいと思います。
その際に引っかかりそうなポイントなどあればご指摘お願いします。

2020-10-16 10:32 UTC, cacapon requested changes
テスト自体の構成に難ありと見受けました。
確認をお願いいたします。

2020-10-16 10:32 UTC, cacapon commented on test/module_test/test_write_reject_command.py
> +from module.read_country_ip import ReadCountryIP
機能を見る限り、実際に処理を行っている個所なので、
テストとしてはユニットテストになるかと思いますが…

reject_command.pyの確認をするのに、ReadCountryIPを使っているのは、
その関数を使わないとテストできないという事なので、依存が出来ており、保守性が悪いです。
ユニットテストとしてはアカンやつです。

WriteRejectCommandのみでテストが完結できるように、
実装を考えてみてください。(例えば、IPの部分はモックに置き換えるとか)

2020-10-18 01:41 UTC, au-niji commented on test/module_test/test_write_reject_command.py
> +from module.read_country_ip import ReadCountryIP
@cacapon
コメントありがとうございます。
他のモジュールは使うべきではないことが分かりました。
必要な出力をテストファイルに保存してやろうと思います。

2020-10-19 01:12 UTC, cacapon requested changes
テスト内容はLGTMです。
一部pep8準拠じゃないところがありましたので、
そこを修正頂ければと思います。

2020-10-19 01:12 UTC, cacapon commented on test/module_test/test_write_reject_command.py
> +'gcloud compute firewall-rules create foreign-reject-test1-000 \
継続行のインデントがありません。

参考
https://qiita.com/KuruwiC/items/8e12704e338e532eb34a

E122

2020-10-19 01:12 UTC, cacapon commented on test/module_test/test_write_reject_command.py
> +'gcloud compute firewall-rules create foreign-reject-test3-001 \
継続行のインデントがありません。

参考
https://qiita.com/KuruwiC/items/8e12704e338e532eb34a

E122

2020-10-19 01:12 UTC, cacapon commented on test/module_test/test_write_reject_command.py
> +    assert os.path.exists(path) == False
comparison to False should be 'if cond is False:' or 'if not cond:'
False との比較を等価演算子を用いて行っています。`==` ではなく `is` を使ってください。 

参考
https://qiita.com/KuruwiC/items/8e12704e338e532eb34a
E712

2020-10-19 01:12 UTC, cacapon commented on test/module_test/test_write_reject_command.py
> +    assert os.path.exists(path) == True
comparison to True should be 'if cond is False:' or 'if not cond:'
True との比較を等価演算子を用いて行っています。`==` ではなく `is` を使ってください。 

参考
https://qiita.com/KuruwiC/items/8e12704e338e532eb34a
E712

2020-10-19 05:12 UTC, au-niji commented on test/module_test/test_write_reject_command.py
> +'gcloud compute firewall-rules create foreign-reject-test1-000 \
@cacapon
ご指摘ありがとうございます。
PEP8に準拠するように修正します。

2020-10-19 05:12 UTC, au-niji commented on test/module_test/test_write_reject_command.py
> +'gcloud compute firewall-rules create foreign-reject-test3-001 \
@cacapon
ご指摘ありがとうございます。
こちらもPEP8に準拠するように修正します。

2020-10-19 05:13 UTC, au-niji commented on test/module_test/test_write_reject_command.py
> +    assert os.path.exists(path) == True
@cacapon
ご指摘ありがとうございます。
こちらもPEP8に準拠するように修正します。

2020-10-19 05:22 UTC, cacapon approved these changes
LGTM

2020-10-19 05:23 UTC, merged