一連の流れの実装
au-niji/ip_rejector pull request #6
Opened 2020-10-19 07:12 UTC by au-niji

# 概要
以下のような流れを一連の動作として実行するようにする
1. `application/ipv4/` の中のテキストファイルを読み込み
2. `application/module/reject/reject_by_country.gcsh_` にコマンドを書き込む

`ipv4` の中に国別のテキストファイルを追加することで、対応する国を増やすことができます。
実行すると`reject_by_country.gcsh_` の存在を確認・削除しているので、実行前に削除する必要はありません。

# 確認方法
.envファイル内のexecution_env=PRODに設定
docker-compose up -d
docker-compose exec app bash
python app.py
テストの場合はexecution_env=testに設定
pytest ../test/module_test/test_app.py

# 懸念点
app.pyという名称でいいのか、クラスにする必要があるのかが曖昧な理解になっています。こうする方がいいという場合がありましたら、遠慮なくご指摘をお願いします。

2020-10-19 07:39 UTC, cacapon commented
そろそろ本番に近い挙動になってくるので、
コンテナ内部に入って実行から卒業してもいいかも。

pytestも出来ればワンコマンドでパス指定なしでできたらありがたいなぁと思います。

2020-10-19 08:05 UTC, cacapon approved these changes
LGTMです。
別途コメントについては別の機会にでもご検討いただければありがたいです。

2020-10-19 08:07 UTC, cacapon commented
追伸：懸念点に関しては私も良く迷うところで…
私でもあの形にしておりますが、ベストかは分かりません…

2020-10-19 08:10 UTC, Amazingengine-yoshitaka requested changes
@au-niji 出力後の program の file の path を `無視 list` に入れて下さい。

2020-10-19 08:10 UTC, Amazingengine-yoshitaka commented on application/app.py
> +TEST_REJECT_FILE_PATH = './../test/module_test/reject/reject_by_country.gcsh_'
二重化してます。

2020-10-19 08:10 UTC, Amazingengine-yoshitaka commented on application/app.py
> +REJECT_FILE_PATH = './reject/reject_by_country.gcsh_'
output 先 `output` 等の directory で御願い致します。 拡張子は `.gcsh` で良いと思いますよ。

2020-10-19 08:10 UTC, Amazingengine-yoshitaka commented on test/module_test/test_app.py
> +TEST_REJECT_FILE_PATH = './../test/module_test/reject/reject_by_country.gcsh_'
二重化してます。

2020-10-19 08:25 UTC, Amazingengine-yoshitaka reviewed
@au-niji 後、これは、佐藤さんのものなので指摘と言う事では無いですが l_ や c_ って略し方が大胆過ぎると思います。

2020-11-06 06:56 UTC, cacapon reviewed
指摘箇所の修正についてはまだのようでしたので、新しくコメントいたしました。

2020-11-06 06:56 UTC, cacapon commented on application/app.py
> +REJECT_FILE_PATH = './reject/reject_by_country.gcsh_'
@au-niji 
上記についての回答か修正をお願いいたします。

2020-11-06 06:56 UTC, cacapon commented on application/app.py
> +TEST_REJECT_FILE_PATH = './../test/module_test/reject/reject_by_country.gcsh_'
@au-niji もう一つ @Amazingengine-yoshitaka  から指摘を受けている
`test_app.py` でも同じ変数が定義されています。

これをどこか一箇所にまとめる対応をお願いできますでしょうか？

2020-11-13 05:57 UTC, au-niji commented on application/app.py
> +TEST_REJECT_FILE_PATH = './../test/module_test/reject/reject_by_country.gcsh_'
@cacapon
返信が遅れてしまい申し訳ございません。
ご指摘ありがとうございます。
ファイルパスを1つにまとめて再度コミットしようと思います。

2020-11-13 05:58 UTC, au-niji commented on application/app.py
> +REJECT_FILE_PATH = './reject/reject_by_country.gcsh_'
@cacapon @Amazingengine-yoshitaka
返信が遅れてしまい申し訳ございません。
出力先をdirectoryにして、ファイル名は別の形で指定するようにしようと思います。

2020-11-13 08:40 UTC, Amazingengine-yoshitaka commented on application/app.py
> +REJECT_FILE_PATH = './reject/reject_by_country.gcsh_'
@au-niji `output/*` 等の分かり易い出力先(output が付いているので出力先)にしておいた方が管理し易いので宜しく御願い致します。
`*` は `wild card` の意味です。

2020-11-13 08:55 UTC, au-niji commented on application/app.py
> +REJECT_FILE_PATH = './reject/reject_by_country.gcsh_'
@Amazingenfine-yopshitaka
コメントありがとうございます。
出力先のフォルダ名を改名して対応しようと思います。

2020-11-13 13:55 UTC, Amazingengine-yoshitaka approved these changes
@au-niji LGTM

2020-11-13 14:07 UTC, merged